=== Michael-G-2000/Work-Portfolio/XML Schema Checking/rentalRecords.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!--
 This document contains the schema for rentalRecord.xml

 Filename: rentalRecords.xsd
 Author: Michael Giglio
 Student ID: 19399805
 Date: 10/09/2020
-->
<xs:schema xmlns:xs='http://www.w3.org/2001/XMLSchema'>
  <!-- User defined types -->
  <xs:simpleType name='custNumType'>
    <xs:restriction base='xs:string'>
      <xs:pattern value='[A-Z]{2}[0-9]{6}'/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name='regoType'>
    <xs:restriction base='xs:string'>
      <xs:pattern value='[A-Z]{3}[0-9]{3}'/>
    </xs:restriction>
  </xs:simpleType>

  <!-- Simple elements -->
  <xs:element name='customerNum' type='custNumType'/>
  <xs:element name='regoNum' type='regoType'/>
  <xs:element name='booked' type='xs:date'/>
  <xs:element name='pickUp' type='xs:date'/>
  <xs:element name='daysRented' type='xs:integer'/>
  <xs:element name='dailyCost' type='xs:decimal'/>
  <xs:element name='charge' type='xs:decimal'/>

  <!-- Attributes -->
  <xs:attribute name='recordNum' type='xs:integer'/>
  <xs:attribute name='full' type='xs:boolean'/>

  <!-- Complex elements -->
  <xs:element name='date'>
    <xs:complexType>
      <xs:sequence>
        <xs:element ref='booked'/>
        <xs:element ref='pickUp'/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:element name='fuel'>
    <xs:complexType>
      <xs:sequence>
        <xs:element ref='charge' minOccurs='0' maxOccurs='1'/>
      </xs:sequence>
      <xs:attribute name='full' type='xs:boolean'/>

    </xs:complexType>
  </xs:element>

  <xs:element name='booking'>
    <xs:complexType>
      <xs:sequence>
        <xs:element ref='customerNum'/>
        <xs:element ref='regoNum'/>
        <xs:element ref='date'/>
        <xs:element ref='daysRented'/>
        <xs:element ref='dailyCost'/>
        <xs:element ref='fuel' minOccurs='0' maxOccurs='1'/>
      </xs:sequence>
      <xs:attribute ref='recordNum' use='required'/>
    </xs:complexType>
  </xs:element>

  <xs:element name='rentals'>
    <xs:complexType>
      <xs:sequence>
        <xs:element ref='booking' minOccurs='0' maxOccurs='unbounded'/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

</xs:schema>

=== Michael-G-2000/Work-Portfolio/XML Schema Checking/rentalRecords.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="rentals.xsl"?>
<!--
 This document contains data for rental bookings of Rent-a-Car

 Filename: rentalRecords.xml
 Author: Michael Giglio
 Student ID: 19399805
 Date: 03/09/2020
-->
<rentals
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:noNamespaceSchemaLocation="rentalRecords.xsd">
  <booking recordNum='4698'>
    <customerNum>BL343456</customerNum>
    <regoNum>DWR654</regoNum>
    <date>
      <booked>2019-10-10</booked>
      <pickUp>2020-12-09</pickUp>
    </date>
    <daysRented>6</daysRented>
    <dailyCost>85.00</dailyCost>
    <fuel full='false'>
      <charge>45.00</charge>
    </fuel>
  </booking>
  <booking recordNum='4732'>
    <customerNum>TR567903</customerNum>
    <regoNum>ABC123</regoNum>
    <date>
      <booked>2019-11-24</booked>
      <pickUp>2020-01-01</pickUp>
    </date>
    <daysRented>4</daysRented>
    <dailyCost>80.00</dailyCost>
    <fuel full='true'>
    </fuel>
  </booking>
  <booking recordNum='4825'>
    <customerNum>VL305888</customerNum>
    <regoNum>XYZ987</regoNum>
    <date>
      <booked>2020-05-10</booked>
      <pickUp>2020-05-15</pickUp>
    </date>
    <daysRented>8</daysRented>
    <dailyCost>49.00</dailyCost>
    <fuel full='true'>
    </fuel>
  </booking>
  <booking recordNum='4920'>
    <customerNum>AG123456</customerNum>
    <regoNum>XYZ987</regoNum>
    <date>
      <booked>2020-08-31</booked>
      <pickUp>2020-09-21</pickUp>
    </date>
    <daysRented>30</daysRented>
    <dailyCost>37.00</dailyCost>
  </booking>
  <booking recordNum='4673'>
    <customerNum>BL343456</customerNum>
    <regoNum>BBB333</regoNum>
    <date>
      <booked>2020-08-31</booked>
      <pickUp>2020-12-12</pickUp>
    </date>
    <daysRented>10</daysRented>
    <dailyCost>60.00</dailyCost>
  </booking>
</rentals>
